name: run checks
on:
  push:
    branches-ignore:
      - master
jobs:
  check_min:
    name: Check with `su6 all` on lowest Python
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - uses: yezz123/setup-uv@v4
        with:
          uv-venv: ".venv"
      - run: uv pip install su6[all] .[dev,all]
      - run: su6 all --coverage 100

  check_max:
    name: Check with `su6 all` on highest Python
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.14'
          allow-prereleases: true
      - uses: yezz123/setup-uv@v4
        with:
          uv-venv: ".venv"
      - run: uv pip install su6[all] .[dev,all]
      - run: su6 all --coverage 100
